# Generated by Django 2.2.2 on 2019-07-28 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StockData', '0002_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='STK_Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stk_code', models.CharField(max_length=30)),
                ('stk_Desc', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='STK_Sentiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stk_SentimentInd', models.IntegerField(default=0)),
                ('stk_DtTmofChg', models.DateTimeField(verbose_name='DtTm of Change')),
                ('stk_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StockData.STK_Code')),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
