# Generated by Django 2.1.3 on 2019-07-29 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StockData', '0003_auto_20190727_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='STK_TrigSent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stk_TrigStat', models.IntegerField(default=0)),
                ('stk_TrigDtTm', models.DateTimeField(verbose_name='DtTm of Change')),
                ('stk_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StockData.STK_Code')),
            ],
        ),
    ]
