# Generated by Django 2.2.2 on 2019-08-03 22:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockData', '0004_stk_trigsent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stk_sentiment',
            name='stk_DtTmofChg',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 3, 17, 7, 24, 818357)),
        ),
        migrations.AlterField(
            model_name='stk_trigsent',
            name='stk_TrigDtTm',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 3, 17, 7, 24, 818009)),
        ),
    ]
