# Generated by Django 2.2.2 on 2019-08-03 22:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('StockData', '0005_auto_20190803_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stk_sentiment',
            name='stk_DtTmofChg',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='stk_trigsent',
            name='stk_TrigDtTm',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
